### PR TITLE
Don't crash with a buffer underflow when packageCount == 0

### LINKED ISSUE #125: Bug: crash when trying to parse some APK files
v2.6.10

Using my own test of going over all installed apps and their APK files ([here](https://github.com/AndroidDeveloperLB/apk-parser)), I've noticed that some APK files cause a crash when trying to parse them.

For example, I get this exception when trying to get the resource table:

```
E: FATAL EXCEPTION: Thread-2
    Process: com.lb.apkparser, PID: 27643
    java.nio.BufferUnderflowException
        at java.nio.Buffer.nextGetIndex(Buffer.java:521)
        at java.nio.HeapByteBuffer.getShort(HeapByteBuffer.java:258)
        at net.dongliu.apk.parser.utils.Buffers.readUShort(Buffers.java:25)
        at net.dongliu.apk.parser.parser.ResourceTableParser.readChunkHeader(ResourceTableParser.java:167)
        at net.dongliu.apk.parser.parser.ResourceTableParser.parse(ResourceTableParser.java:60)
        at com.lb.apkparser.apk_info.ApkInfo$Companion.getApkInfo(ApkInfo.kt:34)
        at com.lb.apkparser.MainActivity$performTest$1.invoke(MainActivity.kt:89)
        at com.lb.apkparser.MainActivity$performTest$1.invoke(MainActivity.kt:21)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
I: Sending signal. PID: 27643 SIG: 9
```

Attached here the problematic APK files:

[problematic apks.zip](https://github.com/hsiafan/apk-parser/files/4476682/problematic.apks.zip)

### PR DESCRIPTION
**Pull request by paulo-raca**
This fixes #125

I don't normally see this issue, the particular exception is on `com.citymapper.app.release`, 
 versionCode 1009500, inside `split_kyc2.config.xxxhdpi`

### CODE REVIEW

**Comment by AndroidDeveloperLB** [comment]
Wait why does it occur? Did you run the sample app I've put against the APK files I've attached?

How did you find the cause and the fix? Is it now completely fixed?

**Comment by paulo-raca** [comment]
> Did you run the sample app I've put against the APK files I've attached?

Apologies for being bump, but what sample app? Attached where?

However I did run `mvn test`

> How did you find the cause and the fix? Is it now completely fixed?

I debugged `ResourceTableParser.parse()` and found that:
- `resources.arsc` is really small (40 bytes)
- `resourceTableHeader.getPackageCount()` is zero
- The string pool is empty
- It reaches the end of buffer right before reading `packageHeader`.

Considering there are zero packages, it seemed reasonable to skip reading `packageHeader`, and it fixes the problem to me.

**Comment by paulo-raca** [comment]
Oh, the `problematic apks.zip` attached to the issue!
I Just tested them, they work fine now :)

**Comment by AndroidDeveloperLB** [comment]
I see. Can you please check the other issues I've reported, too?
Here:
https://github.com/hsiafan/apk-parser/issues/99
https://github.com/hsiafan/apk-parser/issues/108
https://github.com/hsiafan/apk-parser/issues/119
https://github.com/hsiafan/apk-parser/issues/122
https://github.com/hsiafan/apk-parser/issues/123

**Comment by AndroidDeveloperLB** [comment]
I don't see a crash on split_kyc2.config.xxxhdpi .
Can you make a sample to show that it crashes, using the official repository?

**Pull request merged**
